* GymRat
  A simple workout logging application
** Commits
*** June 12th 2017
    - Add exerciseName input suggestions via AutoCompleteTextView
    - Selecting an exercise will update the remaining available information in the exercise prompt
    - Added IO (read/write) for ExerciseManager, WorkoutManager, and WorkoutLogManager
**** TODO Implement a paired entry of reps with weight input
*** June 7th 2017
    - Added an exercise manager, and IO (only input is done, need to complete save to disk feature)
    - Reconfigured Workout and WorkoutInstance structure:
      - A Workout consists of: A name, and a list of exercises (string). *THAT IS ALL*
	#+BEGIN_SRC python
           {
               "Name": "Some Name",
               "Tags": ["Some value", "Some other value"],
               "Exercises": ["String key for exercise1", "String key for exercise2"]
           }
	#+END_SRC 

      - A WorkoutInstance consists of: A name, a list of reps, and rest
	#+BEGIN_SRC python
          {
                "Name":"Default_Chest2",
                "ExerciseList":[
                  {
                    "Name":"Bench Press",
                    "Reps":[
                      12,
                      10,
                      8,
                      8,
                      5
                    ],
                    "Rest": 60
                  }
                ],
                "Tags": ["Chest"]
          }
	#+END_SRC
      - Exercise information must be pulled from exerciseManager, using the name as a key
	#+BEGIN_SRC python
          {
              "Name": "Run",
              "Description": "Lift legs off the ground in alternating sequence. ",
              "Type": "CARDIO_FREE"
          }
	#+END_SRC
*** May 27th 2017
    - Refactored project as GymRat (changed graphics accordingly)
    - Added NewWorkoutFragment, allowing user to create and add new workout
      - Requires a workout name, and at least 1 exercise
      - Exercise creation done by AlertDialog with immediate show override to maintain window if form not complete
      - Exercise reps addition by (finally) a reasonably elegant solution, using ViewHolder tag and getLayoutPosition
    - Added long-click menu for workout selection, replacing spinner with ListView
    - Timer toggle allows user to switch in between viewing exercises, and a rest timer with reset button fragment.

*** May 12th 2017
    Replaced clunky addSet feature by adding a WorkoutInstanceManager
    - WorkoutInstanceManager :: Essentially a cached version of the current WorkoutInstance. Allows modification for database IO, and retaining context on fragment navigation
    Use recyclerView for display of editTexts - with InputFilters to only allow #s
*** May 8th 2017
    Added workoutLogging functionality
    - WorkoutInstance :: Extends the workout type, but has a date associated with the workout
    - WorkoutInstanceExercise :: Extends Exercise, has a list of reps associated with it
    - DatabaseIO :: Allows storage of workout and workoutLogs as .json file on local file. Methods locally have a toJSONObject method
*** May 2nd 2017
    Initial commit
    - Workout :: Consists a name, an arbitrary length list of exercises, and an arbitrary length list of associated tags
    - Exercise :: Consists of an ExerciseType, name and description
    - ExerciseType :: One of: MACHINE, BARBELL, DUMBELL, FREWEIGHT, CARDIO_MACHINE, CARDIO_FREE or UNDEFINED (\approx ERROR)
    Contains the necessary fragments for basic navigation
